### ISSUE TITLE
Write about example of how the index work between governments and civil society

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1000]
So we can explain what we expect that will happen

**Comment by dannylammerhirt** [comment]
Consult with GovData Alliance about their experiences

**Comment by dannylammerhirt** [comment]
Relevant learnings from other indicators:

https://www.globalintegrity.org/2017/03/africa-integrity-indicators-data-use-and-impact/

**Comment by dannylammerhirt** [comment]
Governance (or results) data is more likely to have an impact if it adheres to the following principles: 

- [ ] Alignment with country policy priorities; 
- [ ] Contextualization of the data to country-specific realities; 
- [ ] Actionability 
- [ ] Credibility of the assessment in terms of transparency and robustness of the methodology employed

**Comment by dannylammerhirt** [comment]
Problem: 
"Striking the right balance between aligning assessments with ongoing country priorities and allowing for cross-country comparability is a formidable challenge"

**Comment by dannylammerhirt** [comment]
Revisit GODI's Theory of Change:

**Does the availability of governance data, generated through externally-driven assessments translate into better open data publication?**

**Comment by morchickit** [comment]
I collected some real world example from the forum - https://docs.google.com/document/d/1WfeDoKwWYj_F1AaNm2bXzP4CqPVYwPYciU3iLR1vLgM/edit

That should help to write the blog post of the launch!
