### ISSUE TITLE
Upload the research diaries to website

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1001]
Or link to them from the site, so people can use them if they need it to their research

**Comment by morchickit** [comment]
@brew  - maybe we can link to the google doc from the "downlaod" page? Just an easy link to a drive can be sufficient

**Comment by dannylammerhirt** [comment]
Danny to do: write text for the link to the diary folder (what is it for, what can be found there)

**Comment by dannylammerhirt** [comment]
Diaries can be found here: https://drive.google.com/drive/folders/0B5j55T4ZyssBbHBJaS1nblo3WG8

**Comment by brew** [comment]
@dannylammerhirt Is this ready for me to link? There are two links in your comment above, which should I add to the website?

**Comment by dannylammerhirt** [comment]
@brew yes, the link is ready. I removed the second one. Text and link: 

"Click here to find our research diaries. They explain what we have learnt from reviewing each data category, how we dealt with outlier cases, and how we might adapt our future methodology." Link: https://drive.google.com/drive/folders/0B5j55T4ZyssBUTlRbkdvYzhOSkU
