### ISSUE TITLE
Blogpost: How to tell the difference? Spending vs. Procurement vs. Budget (draft finished by Tuesday, May 16)

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1004]
In some cases it has proven challenging to assess spending and procurement data. The data contain overlapping information. 

We will look into a list of portals and identify overlaps, differences between data. 

Output: 
Clear descriptions what identifies each dataset type.
Blogpost about our findings/learnings to sensitise government, the community, civil society.   

This will be done together with the OpenSpending team.

**Comment by dannylammerhirt** [comment]
Our list of portals to look at https://docs.google.com/spreadsheets/d/1zyswzKH7vsPyBpfm682KT5dsDY6j81t30cUDlcKuIGM/edit#gid=0

**Comment by dannylammerhirt** [comment]
Danny to set up a sprint date

**Comment by akariv** [comment]
Let me have a go at this.

*Budgeting* is the process where an organisation decides how to spend an amount of money over a specific time period (usually a year, but not always). While budgeting, the amount is broken into smaller amounts (budget items), each one is classified by one or more of the following classifications:
- Administrative (which sub-unit gets the money)
- Functional (what it's going to be used for)
- Economic (how it's going to be used, e.g., procurement, subsidies, salaries etc.)
- Financing source (where the money should come from).

The *Budgeting Cycle* is the process of creating a budget - it starts with a *proposal* which turns into an *approved* budget. During the budget period some adjustments might be made - which result in a *revised* budget. After the budget period ends, we know how much money was actually spent on each item.

*Spending* is the process of giving away money. Money might be given as a subsidy, as payment for a provided service or as salary (although salaries will seldom be published on a transactional level). The one thing in common among all spending is that the level we're looking for are monetary *transactions*. Each transaction holds the following information:
- The amount that was transferred
- The recipient (an entity *external* to the organisation)
- When the transaction took place
- From which budget item the money came from
- Justification for the transaction

Let's focus on the justification. 
We'll put aside subsidies, as those will usually have a bureaucratic process for allocating them which you could refer to (but it's different from one place to another). 
When purchasing goods or services, most organisations will require a certain process for choosing the supplier who fits best the need. That might involve some sort of tender or other vetting mechanism, meant to prevent corruption. This process is called *procurement*. For large contracts, you might find that one procurement process is later followed by many individual transactions. For example, there might be a construction contractor that's being payed by milestone, or an office supplies dealer which is chosen as a default supplier - then each spending transaction is for a specific item.
The procurement identifier might serve as a justification for a purchase related spending transaction.

Each procurement is, in essence, a contract between the organisation and a supplier. But these are not the only contracts that an organisation might sign on. Others might be contracts for cooperation, sharing knowledge etc. The process of signing such contracts is called *contracting*.

**Comment by dannylammerhirt** [comment]
Last to dos: 
- [ ] add some images that explain the differences between procurement and spending data Adam described
- [ ] @tlacoyodefrijol to add some examples
- [ ] @dannylammerhirt to write final blogpost

**Comment by dannylammerhirt** [comment]
Blogpost draft here: https://docs.google.com/document/d/1NBHk0EpZeaSY7tDqnzuVRAnqhCII3iViWQmMIt9gSSE/edit

**Comment by dannylammerhirt** [comment]
A list of how spending (-related) data is presented: https://docs.google.com/document/d/1bdSOVe8YFu4_d250FAn3Ew1tYcTY3MWF9NHPSzv6WGs/edit

**Comment by dannylammerhirt** [comment]
Draft finished, proof-reading required

**Comment by dannylammerhirt** [comment]
@tlacoyodefrijol draft finished. Proof-reading would be needed
