### ISSUE TITLE
Have a google hangout with the community to explain the GODI results

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1005]

**Comment by dannylammerhirt** [comment]
get the governance data alliance on this call too

**Comment by morchickit** [comment]
@tlacoyodefrijol  - to do:
- Send a schedule invite
- Send a message to the forum
- Tweeter
- Facebook

**Comment by dannylammerhirt** [comment]
Recipients:

- [ ] Open Data Charter adopters and working group members
- [ ] Governance Data Alliance (to learn from the experience of having a public dialogue)???
- [ ] who else?

**Comment by tlacoyodefrijol** [comment]
https://docs.google.com/document/d/10D2oAafF3upHgdCW27VxAr4TXJ-4DbxbV_ucN6_tVQc/edit
