### ISSUE TITLE
Put a warning next to view other years

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1012]
This should be in a text next under the years that says the following:
"Please note that this year's GODI methodology is significantly different than other years and the results can not be comparable over time"

**Comment by morchickit** [comment]
We should ask @smth about it

**Comment by smth** [comment]
I've added something to that effect [here](http://okfnlabs.org/index-mockup/dataset/).

**Comment by dannylammerhirt** [comment]
I like the new wording. Would we include the wording also in the places page (see here: http://index.okfn.org/place/)

**Comment by smth** [comment]
Yeah, should be everywhere that the year links appear. (http://okfnlabs.org/index-mockup/places/)
