### ISSUE TITLE
Prep all social media for launch

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1013]
- [x] prep tweets in English, Spanish, French
- [ ] prep Facebook posts
- [x] Post for OKI Discuss
- [ ] Cool infographic / gifs for the launch? 
- [ ] Schedule and promote a community hangout for the GODI launch 
- [ ] make a spreadsheet to track world mentions 

@tlacoyodefrijol - please add more things we need to prep (if need be!)

**Comment by tlacoyodefrijol** [comment]
So list would be:

- [ ] Tweets about launch
- [ ] Tweets in Spanish
- [ ] Tweets in English
- [ ]  Ask the forum for tweets in other languages

**Comment by tlacoyodefrijol** [comment]
Should we aim for a press release to send to major newspapers or media outlets @morchickit @dannylammerhirt ?

**Comment by morchickit** [comment]
I think we should not for this phase, maybe for the June one.

**Comment by morchickit** [comment]
https://drive.google.com/drive/folders/0B32X1LZrOOhrSUVpNUZMRFVkbGM

**Comment by morchickit** [comment]
@tlacoyodefrijol please close when you think it is done
