### ISSUE TITLE
Explanatory text for 'Percentage Open' on Places page needs review

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1014]
To explain it in two lines!! 
Connect with a link to the open data definition.
Brew to implement after it's done

**Comment by smth** [comment]
I think the first line alone (coupled with a link to the Open Definition) may be enough for a lot of people.
> This is the percentage of all the dataset entries that are open as per the Open Definition.

My slightly longer version would be:
> The percentage of all the dataset entries (an entry is, for example, Taiwan - Government budget, or Australia - National statistics) that are fully open, as per the [Open Definition](http://opendefinition.org/).

Does that give enough of an explanation? And of course, is it accurate?

**Comment by smth** [comment]
A point to clarify: A similar stat was previously stated on the home page, but described as "key datasets". "Key" doesn't seem to be defined anywhere (and the figures are the same). Is this an idea we want to hold on to? Thinking about this in the context of unifying this information site wide.

**Comment by dannylammerhirt** [comment]
@smth I like the second approach you proposed ("Another approach would be to change the initial phrase from % open. to % of dataset entries in the index are open.. Then provide clarifying tooltips for both the words entries and open. This way we could introduce a site wide pattern for offering definitions (as opposed to explanations").

 If I understand correctly you refer to the phrase "9% Percent Open  Down from 12% in 2014", right? I think your proposal of having a longer sentence, and separately explaining entry and open would make this metric  more intuitive. 

Question: would it look good? We would have to think where to put the comparison with last year's results ("Down from 12% in 2014").

**Comment by smth** [comment]
We are dropping the previous year comparisons (this was discussed briefly last week), so we are left with what you see [here](http://okfnlabs.org/index-mockup/places/) (just above the footer).
