### ISSUE TITLE
Minimal design changes for the Index

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1016]
- [ ] Change colour of the header so people can differ between editions 

- [ ] How to implement explanations about the data in the best way

**Comment by smth** [comment]
For the first part, if we are going to change the colours, I suggest we make previous years grey (and add a year to the logo)
<img width="1192" alt="image" src="https://cloud.githubusercontent.com/assets/1375708/25132642/1e54078c-2442-11e7-93a7-bccf0686d780.png">

Can someone remind me what the second part of this issue refers to?

**Comment by morchickit** [comment]
Second part is about explanations -
Do we want to have tool tips or other forms?

**Comment by smth** [comment]
My summary of what I have (from outside of this thread) understood the problem to be:

- There is some additional information that users need on the entry page. Namely "Data format", "Data licence" and "Data Location".
- The crucial content on the entry page is in danger of getting lost amongst the growing supplementary content.

Suggestions:

- The template already has a section for meta data, but is disabled for the GODI instance. This can be enabled and used for this purpose.
- Supplementary content could be hidden by default, making it easier focus on the primary content. I suggest an expand/collapse mechanism.

Example: http://okfnlabs.org/index-mockup/entry/

**Comment by dannylammerhirt** [comment]
I like that suggestion, @smth. The mockup you linked already has loads of content, so agree to keep the amount of information reasonable.

Also agreed to park supplementary information in a expand/collapse mechanism. The metadata section looks like the best place for "Data Format", "Where to find the open license: URL", "Where to find the data: URL".  

Please do feel free to rename these if you think they are too long. 

Also, how about removing "submitter" and "reviewer" from the metadata section, if we keep the separate expand mechanism called "Contributors". I like having an own expand mechanism for this.

**Comment by smth** [comment]
Yeah, ignore the specific content of the meta data section in that mockup.

**Comment by morchickit** [comment]
I actually think that the credits to reviewers and contributors is important, and should be visible always

**Comment by smth** [comment]
In that case, @brew leave the credits out of the collapsible panels. Maybe put them below "meta data".
