### ISSUE TITLE
Add the button of "Discuss findings" to the home page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1017]
So people can go to the forum

**Comment by morchickit** [comment]
Also add to entry page

**Comment by smth** [comment]
Now appears here:

<img width="979" alt="image" src="https://cloud.githubusercontent.com/assets/1375708/25130468/232621c6-243a-11e7-9da5-f6e6382775a4.png">

and here:

<img width="1197" alt="image" src="https://cloud.githubusercontent.com/assets/1375708/25130503/4e1d2924-243a-11e7-8179-208bd6e0ff61.png">

**Comment by morchickit** [comment]
looks good @smth !

**Comment by brew** [comment]
@smth I think changes made to vertically centre the text and buttons here have broken things on the Survey site. Checkout http://global.survey.okfn.org/. There is text that is being cut off under the header. I think this is because the header is now `position: absolute`. Can you take a look?

**Comment by smth** [comment]
Yeah, you're right. CSS should have been more specific. Fixed [here](https://github.com/okfn/census-mockup/commit/6d8b1af5a7f1d1da0f5cacba08623271caa93b5c).

**Comment by brew** [comment]
Fixed by 7f1f78b
