### ISSUE TITLE
Strategy for Index domain

### ISSUE THREAD

**Issue by brew** [okfn/opendatasurvey#1018]
The old (2013, 2014, 2015) Index is served from index.okfn.org as a single website using the old codebase. 

We need to decide from which domain the new (2016) Index will be served, and consider its impact on:

- linking to the old version
- potential issues with local Index sites (e.g. my-city-index.okfn.org)

**Comment by pwalsh** [comment]
Hi. The old ones stay as they are - no need to touch them. The new one can be published to some random AWS domain until date of release, on which we:

- move the 2015 index from index.okfn.org -> 2015.index.okfn.org
- publish the new one on index.okfn.org

**Comment by morchickit** [comment]
@akariv - we need to move the new index site (http://index.okfn.org.s3-website-eu-west-1.amazonaws.com/) to the Index domain only on Tuesday, May 2nd. Is that ok?

**Comment by morchickit** [comment]
@akariv - Can you please discuss with @brew about this to see who will be better to set up the domain on Tuesday? Thanks!

**Comment by morchickit** [comment]
Ok, @akariv will do this on Monday night Portland time. Closing this.
