### ISSUE TITLE
Contrast on the explanation of the open data scores range is too low

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/opendatasurvey#1025]
This is what I'm talking about. The "from 0 to 100" is hard to read, specially the former.

![Contrast with black letters](https://cloud.githubusercontent.com/assets/76945/24710836/33369830-1a16-11e7-85bc-7e56dd1ef4ad.png)

Changing them to white make them easier to read IMHO:

![Contrast with white letters](https://cloud.githubusercontent.com/assets/76945/24710837/33cb4d68-1a16-11e7-9930-302448c0168f.png)

**Comment by morchickit** [comment]
@smth we should look at it next week

**Comment by smth** [comment]
Agreed. They were white in the design ;)

**Comment by smth** [comment]
Fixed [here](https://github.com/okfn/census-mockup/commit/e58f4c1c62c15ecd7d6242a2f7b9dda21887a461) @brew
