### ISSUE TITLE
Clarify what the difference is between country ranking score and the country-specific score

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1026]
The country ranking score (on places page) and the country-specific score (on a country page) are different measurements, but are both expressed as XX% values. This is confusing.

We will keep the overall score of a country to enable a country ranking. 

On a country page we will display the country rank + the number 69% both prominently where the current % is written so that both can be read in context.

**Comment by morchickit** [comment]
@smth - can you have a look at it next week?

**Comment by smth** [comment]
OK. Could someone give me / point me to a description of these two figures, how they differ, how they are derived?

**Comment by dannylammerhirt** [comment]
Country ranking score = the overall score that a country reaches when adding up the points for each dataset of a country. Maximum points are 1500 (100 points x 15 datasets). We do not show the absolute number but a percentage of the total possible score. 

Country-specific score = the percentage of datasets that are open in a country.

**Comment by smth** [comment]
Thanks. And the discrepancy is due to the question weighting, right?

**Comment by dannylammerhirt** [comment]
Not really, the metrics measure different things. The country ranking score adds all points together that each country got for each dataset. So this is the total sum of points to make countries comparable.

The country-specific score basically just states something like: 5 out of 15 datasets are 100% open = 33% of all 15 datasets in this country are open.

**Comment by smth** [comment]
I think the best we can do is label them "open" and "score" and add definitions. It might also help to present them in a similar context to the scores in the comparison table. Something like [this](http://okfnlabs.org/index-mockup/place/).

**Comment by morchickit** [comment]
Sounds like a good solution, but I wonder if we can do it. 
@brew - is all the data available?
