### ISSUE TITLE
Mention all organisations on About-page, that consulted us, or whom we draw inspiration from

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1031]
Feedback on survey design: (from this doc: https://docs.google.com/document/d/1lbLjBgTl94GAD3XIuIYRBbvZ4H4Y4Zg77EdSgj-0Cho/edit)
Livar Bergheim (),  Owen Boswarva (), Ana Brandusescu (World Wide Web Foundation), Pierre Chrzanowski (), Stephen Gates, Augusto Herrmann (), Carlos Iglesias (World Wide Web Foundation), Hazwany Jamaludin (Sinar Project),  Benjamin Ooghe-Tabanou (), Iris Palma (), Juan Pane (),    Pieter-Jan Pauwels (Open Knowledge Belgium), Nisha Thompson (Datameet), Lorenzino Vaccari (), Christopher Wilson (University of Bergen)

Dataset consultants: 
Legislative data: Greg Brown (National Democratic Institute)
Election data: Michael McNulty, Michelle Brown (National Democratic Institute)
Land ownership data: Frank Pichel, Lindsay Ferris (Cadasta Foundation Fellowship) 
Weather forecast data: Ben Schaap (Global Open Data for Agriculture and Nutrition)
Methodological advise: Tim Davies (Open Data Services)

**Comment by dannylammerhirt** [comment]
Open Data Services - research advice

National Democratic Institute

Cadasta Foundation: fellowship

**Comment by morchickit** [comment]
@tlacoyodefrijol and @dannylammerhirt - do we want to acknowledge our wrangler and reviewers in the about page as well?

**Comment by morchickit** [comment]
@dannylammerhirt - I added the people I know about. Maybe @KateRogers know of others?

**Comment by tlacoyodefrijol** [comment]
I would acknowledge at least the Wranglers. 
Reviewers would be nice as well.

**Comment by dannylammerhirt** [comment]
+1 for reviewers & wranglers

**Comment by dannylammerhirt** [comment]
@tlacoyodefrijol can you add the wranglers here? Then I'll copy the names in the About text and close issue
