### ISSUE TITLE
Clarify how we asses water quality

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1033]
In past editions GODI assessed water quality "at the water source". 

This leaves room for interpretation: are we talking about drinking water supply/sources, or about environmental water such as groundwater. 

This document (https://docs.google.com/document/d/1VQAPU5KF-qegcZQjdLjHdrtIK5zTslopk96IdLRaxpU/edit)
explains our approach how to assess water quality

**Comment by dannylammerhirt** [comment]
@morchickit if governments asks us how we assessed water quality, the doc above will be our answer

**Comment by morchickit** [comment]
+1
