### ISSUE TITLE
Create an FAQ page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1037]
Topics - 
 - Dialogue phase
- Research process
- how to contact us

**Comment by morchickit** [comment]
Link to the FAQ - https://docs.google.com/document/d/15wOjf8cTm0RKlg9HyOvr_zi7MsVtAG8RAMh_XgGwGOs/edit

**Comment by dannylammerhirt** [comment]
@morchickit made my changes, looks all good IMO

**Comment by morchickit** [comment]
In the config sheet.
