### ISSUE TITLE
Fix the tables design on the content pages

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1041]
Currently, we use markdown for the content pages. When uploading a table to the the new Index site, their design makes them hard to read: http://index.okfn.org.s3-website-eu-west-1.amazonaws.com/methodology/

See how their design should look here: http://index.okfn.org/methodology/

**Comment by brew** [comment]
There's good news and bad news.

Bad news:
You won't be able to use markdown to write the tables.

Good news:
You can use raw html markup to write the tables. This is what the old Index did too (see the tables mark up here: https://raw.githubusercontent.com/okfn/opendataindex/master/content/pages/methodology.md).

It's important that the table tag includes the correct classes, as in the old version:

```html
<table class="table table-striped table-bordered">
```

I'll reassign this to you so you can mark up the tables as raw html.

**Comment by morchickit** [comment]
OK, it works! THnka Brook! Closing it.
