### ISSUE TITLE
Add static pages to the tool bar

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1043]
- [ ] FAQ
- [ ] How to read the reuslts

**Comment by brew** [comment]
We're getting to the point where there are too many navigation links across the top. Can some of these be added as sections to a single page? Can 'How to read...' be a section in Insights, perhaps?

<img width="1238" alt="screen shot 2017-04-21 at 13 24 42" src="https://cloud.githubusercontent.com/assets/3993/25277336/1e7ab85e-2696-11e7-88f6-8c0830274ac5.png">
