### ISSUE TITLE
Write a blog post announcing the launch

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1045]
Make sure to have a blog announcement for 2nd of May. 
- Mor to write
- Oscar to proofread

**Comment by morchickit** [comment]
Can be found here: https://docs.google.com/document/d/1UgRUhHhH7mjWb7cy6iUeuQfleduBvzUl8e2gXLcoAJA/edit#

**Comment by morchickit** [comment]
Done, thanks to @jobarratt ! :-)

**Comment by dannylammerhirt** [comment]
@morchickit can you check my edits? I found some typos in the document
