### ISSUE TITLE
Breadcrumb links inaccessible on places and datasets page

### ISSUE THREAD

**Issue by brew** [okfn/opendatasurvey#1047]
Recent design changes to the /datasets and /places page have moved the share widget. This now prevents the breadcrumb links from being accessible on these page. Checkout:

http://index.okfn.org.s3-website-eu-west-1.amazonaws.com/place/
http://index.okfn.org.s3-website-eu-west-1.amazonaws.com/dataset/
http://okfnlabs.org/index-mockup/place/
http://okfnlabs.org/index-mockup/places/

**Comment by smth** [comment]
It was the container now having position relative, being in front of the breadcrumb. [Giving the breadcrumb a z-index](https://github.com/okfn/census-mockup/commit/f9fdf43a73f6601125afbeb35b485be446cfd5b4) fixes [this](http://okfnlabs.org/index-mockup/places/) (could have removed the position absolute from the breadcrumb, but I assume it's there for a reason).
