### ISSUE TITLE
Change Icons alt text

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1061]
See what happen when the timely icon uses the long questions text from the spreadsheet 
![screen shot 2017-04-26 at 16 03 40](https://cloud.githubusercontent.com/assets/3273659/25441440/284a0cd8-2a9a-11e7-87b4-69ad59a3b6af.png)

Maybe we can just use the short texts instead?

**Comment by brew** [comment]
Only half of this issue was fixed. We still need to correctly render the question text in entry pages, in the presence of a dataset context.
