### ISSUE TITLE
Align images on Insights page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1069]
- [x] Add   images/Datagapsclean.jpg after the second paragraph

- [x]  Add  images/findabillity.jpg after the third bullet point and make it smaller. Maybe 400X200? 

Both in the middle of the page

**Comment by brew** [comment]
Images added to markdown doc with a special bootstrap class and style. This centers the image and gives them a max-width, e.g.:

```html
<img src="/images/Datagapsclean.jpg" alt="Data gaps" class="img-responsive center-block" style="width: 700px;">
```

@mor, please check on the site, and close this issue if you're happy.
