### ISSUE TITLE
Remove formatting errors from methodology page

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1086]
The data category table contains some formatting errors such as italics, missing bullet points, etc. We need to correct this

**Comment by dannylammerhirt** [comment]
@morchickit I tried to fix this with @tlacoyodefrijol, since you built this, do you want to take over, so nothing breaks? Otherwise I'm happy to take over today

**Comment by dannylammerhirt** [comment]
Add weather data category to our methodology page

**Comment by svanderwaal** [comment]
I've done a review on these and updated the config spreadsheet, so this can be pushed live.
