### ISSUE TITLE
Add sponsors logo to the site

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#1088]
@brew - IDRC want their credit ASAP (can't blame them) can we add to the bottom "supported by OD4D" 
Brand guides are here - https://docs.google.com/document/d/1VdFFEG3XNbTRtVBbqeLkZ8chElaCUDq2mRIywELkZaM/edit
I will add the text to the about page.

**Comment by morchickit** [comment]
Logo is here: https://drive.google.com/drive/u/1/folders/0B9iSbTv-uxu9fjE2S1VfYmh4eXNzQ2h5Z3dpWTlURkFmeXlubkFybXREYll3RDVBNHlhNzg

**Comment by brew** [comment]
Where should the logo go go?

**Comment by morchickit** [comment]
On the footer please.

**Comment by brew** [comment]
Should this logo be linked to somewhere?

**Comment by KateRogers** [comment]
If you can link the logo to http://od4d.net/ that would be great

**Comment by morchickit** [comment]
This is done!
