### ISSUE TITLE
Correct false spending entries

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1099]
our results contain many false spending entries. We sometimes assessed implemented budget as spending, sometimes procurement contracts or else.

We need to correct these entries and set them to 0%

1) Populate list of spending entries that are currently scored - check if these entries actually refer to transactional data. List available [here](https://docs.google.com/spreadsheets/d/16ARZ8bmk-2HpFOEYPtWlrp_XTas8qRWO6zSm3mPxZR4/edit#gid=1160760693)

2) implement changes

**Comment by morchickit** [comment]
You want me to review everything that has a score that is bigger than 0% ?

**Comment by dannylammerhirt** [comment]
Yes, not sure about the exact number, but I revisited at least half of it already. We can discuss in our first sprint call.

**Comment by dannylammerhirt** [comment]
@morchickit can we close this?  I saw that there are some outstanding spending entries. e.g from Mexico in our public dialogue spreadsheet (the long list, not your shortened spending list). Can you look into that too?
