### ISSUE TITLE
Collect press mentions

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1103]
We need to monitor which media outlets report on GODI and how. 

Our monitoring list can be found here: https://docs.google.com/spreadsheets/d/10IID9rA_tQBFqqmFhVYB0uIjpy-0_ECQwV_Id9I9UsY/edit?ts=5922f68d#gid=0

**Comment by FrankaVaughan** [comment]
Will update the list on Friday.
