### ISSUE TITLE
Collect examples of good discussions during public dialogue & user contacts

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1106]
The public dialogue brought up very constructive feedback for the Index process and final results.

@dannylammerhirt will collect these examples in this spreadsheet https://docs.google.com/spreadsheets/d/16ARZ8bmk-2HpFOEYPtWlrp_XTas8qRWO6zSm3mPxZR4/edit#gid=1334486542

and will add these to the final report (user engagement section)

**Comment by dannylammerhirt** [comment]
@tlacoyodefrijol, @FrankaVaughan, if you come across helpful dialogues, ideas for improvement, or anything else that is noteworthy for us, please fill it into this sheet: https://docs.google.com/spreadsheets/d/16ARZ8bmk-2HpFOEYPtWlrp_XTas8qRWO6zSm3mPxZR4/edit#gid=1334486542

**Comment by morchickit** [comment]
@dannylammerhirt - I added some - see if it's what you mean?
