### ISSUE TITLE
Write GODI section of Hewlett year 1 final report (submission due 11th August 2017)

### ISSUE THREAD

**Issue by StephenAbbott** [okfn/opendatasurvey#1116]
Our Hewlett year 1 report on GODI and other Hewlett-funded activities is due to be submitted by 11th August 2017.

See Trello card for more details: https://trello.com/c/3QtcoJIt/12-1484-hewlett-yr-1-final

**Comment by StephenAbbott** [comment]
Make sure to speak to @dannylammerhirt to build in the metrics work done on the GODI final report appendices which were withdrawn for the sake of space

**Comment by dannylammerhirt** [comment]
@tlacoyodefrijol can elaborate on metrics for the survey phase (unique contributors) etc.

**Comment by dannylammerhirt** [comment]
Hi @StephenAbbott, can you tell me where you put the metrics from our final report appendix? (i.e. the user engagement figures)

**Comment by StephenAbbott** [comment]
@dannylammerhirt Here's the Google doc https://docs.google.com/document/d/1hwNDRuCyGojSHLFzde97nD_B9llvRIIvv8CV7JywsUA/edit Scroll to bottom

**Comment by StephenAbbott** [comment]
Hewlett reporting Google doc = https://docs.google.com/document/d/1kSCPu_5KEzqIhP-Jb8LeWlkwtWl7B3b86gVuU7e1PXw/edit?ts=598a28dc
