### ISSUE TITLE
Create comms plan for final GODI launch

### ISSUE THREAD

**Issue by StephenAbbott** [okfn/opendatasurvey#1117]

**Comment by dannylammerhirt** [comment]
@tlacoyodefrijol: 


https://docs.google.com/document/d/1uNAln9QxLsOKoLv0SrU-OT2xfT1hXDQVD22V-YN15ss/edit

**Comment by dannylammerhirt** [comment]
+tlacoyodefrijol to add link to Cadasta blogpost in final report and tweet about it

**Comment by tlacoyodefrijol** [comment]
Document with launch tweets and posts
https://docs.google.com/spreadsheets/d/1FGR-6sadv0mcEcqSHvt-BWsHkbUkjTqsNy3sYbXBXhQ/edit#gid=0
