### ISSUE TITLE
Update Methodology or Insights section of GODI website to link to final report

### ISSUE THREAD

**Issue by StephenAbbott** [okfn/opendatasurvey#1132]
Could we please update the https://index.okfn.org/insights or https://index.okfn.org/methodology pages on GODI website to link to the PDF of the final GODI report we produced?

https://blog.okfn.org/files/2017/06/FinalreportTheStateofOpenGovernmentDatain2017.pdf

**Comment by dannylammerhirt** [comment]
I committed changes to the insights page: https://github.com/okfn/opendatasurvey/blob/master/content/insights.
