### ISSUE TITLE
Create list of existing tutorial material for GODI

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1137]
Cecile will run a workshop in Francophone African countries to teach how to use GODI. 

She offered to translate our current guidance material as well as the survey interface.

This is an excellent opportunity because we can use this as a way to improve our additional current guidance material for the submission and review phases. 

The guidance material for the submission phase can be found here:

The guidance material for the review phase can be found here:

**Comment by dannylammerhirt** [comment]
Also Cecile can look at the review guidance material (especially section 'reviewing the survey questions'). The guidance is available here: https://docs.google.com/document/d/1drEj8cBVVxP7Ri-4SMIUsOdP6lLNcpQShpkx0rRdJLQ/edit

Also useful could be our guidance on how to find and identify key datasets: https://docs.google.com/document/d/1IRD1o1dcdMyfPP5Eyx6HeGHs2s_bb9JU9Acbn9u4N14/edit

**Comment by StephenAbbott** [comment]
Open Data Survey instances registry https://docs.google.com/spreadsheets/d/1eOoISLZlurX8McPGxiG47FkdKxfAXRuogxNdy0ZcGQQ/edit#gid=0
