### ISSUE TITLE
Implement question_set for the Africa Data Index survey into the flat CSV (current) file

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#1161]
The African open data survey includes a customised question set which differs slightly from the question set we are using for the GODI instance. See question sets here: https://docs.google.com/spreadsheets/d/1GtnNJjD1zDcG3ydmODc9UmO0fZX6pPNNYU8Z5kS_Dq0/edit#gid=235252093  

We are planning to implement a flat CSV file to make the Africa open data survey results more easily usable.

We need to change the column headings in the current flat CSV file @roll developed to take into account the ADRR question set. In the following file I marked questions we need to add and remove from the current flat CSV: https://docs.google.com/spreadsheets/d/1nZlnVbvZvRu2U4n59NU07-_hu1ZwFZBqM7eStlVP6Fo/edit#gid=661481897

To implement the question set, @roll estimates another 2-4 hours work time.

**Comment by roll** [comment]
A quick implementation note - we just need to make this code - https://github.com/okfn/opendatasurvey/blob/master/census/controllers/api.js#L324-L401 - to iterate over questions and write columns automatically. Should be pretty trivial.

**Comment by jobarratt** [comment]
@dannylammerhirt what's your deadline for this? We can definitely fit it in

**Comment by jobarratt** [comment]
@brew i think it would be good if you could fit this in before the end of the week if possible. Evgeny estimates the task at less than 4h.

**Comment by dannylammerhirt** [comment]
@jobarratt this Friday would be excellent. Thanks so much for the swift response!

**Comment by brew** [comment]
@dannylammerhirt This is done and pushed to production. Worth you having a look.

**Comment by dannylammerhirt** [comment]
@brew excellent work, the file continues all we need! Thanks so much.
