### ISSUE TITLE
Date data made available question displayed in {{questions}} but not collected

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatasurvey#580]
Date the data was made available is displayed but the question is not presented in the submission form.

<img width="971" alt="screenshot 2015-07-23 00 19 53" src="https://cloud.githubusercontent.com/assets/9379524/8827580/d40eed24-30d0-11e5-8c2b-bf3e1afe34e2.png">

The question is displayed in {{questions}} - as is other questions not captured e.g. Rate Quality of Data (Structure)

<img width="828" alt="screenshot 2015-07-23 00 25 39" src="https://cloud.githubusercontent.com/assets/9379524/8827681/69424f6c-30d1-11e5-9887-940b72e276fb.png">

**Comment by pwalsh** [comment]
@morchickit what is the bug, exactly:

1. The fact that we still display a UI element for "date available"?
2. The fact that we don't show a question anymore for data available?

I'm sure it is 1 - we removed this question in previous years, but I want to ensure that you agree: the action I should take is removing the display of "date available" from the information row for an entry.

**Comment by morchickit** [comment]
This can confuses me. Can we skype about it ?

**Comment by pwalsh** [comment]
yep

**Comment by Stephen-Gates** [comment]
Sorry If I've caused confusion. 
 - Recent changes have fixed 2 - the question isn't asked in the submission form or shown in {{questions}}  E.g. [working here](http://australia.census.okfn.org/faq/#questions). 
 - So, in my mind the question is, should we still display a calendar icon for `date available`?

The current behaviours are valid and you could close this issue now.

My question is, 
- do you want to keep the calendar icon on /places/placename to show the  `date available` from prior census years?

or
-  remove the calendar icon as it is not relevant going forward? 

You're call - I can see arguments for either.

**Comment by pwalsh** [comment]
WONTFIX. No longer relevant. Belongs to old codebase only.
