### ISSUE TITLE
Methodology to the local index should be stated somewhere on the instance

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#745]
Currently, all local index are using the global methodology, but don't link to it. We need somehow to link it.

**Comment by Stephen-Gates** [comment]
Feel free to use this http://australia.census.okfn.org/faq/

**Comment by brew** [comment]
@morchickit Methodology is now an optional top-level navigation item, defined in the site-config under the `methodology_page` key (#831). Does that fix this issue?

**Comment by pwalsh** [comment]
Closing. Please reopen a new issue with specific details if still relevant.
