### ISSUE TITLE
Thematic Review Guide

### ISSUE THREAD

**Issue by tlacoyodefrijol** [okfn/opendatasurvey#799]

**Comment by dannylammerhirt** [comment]
@tlacoyodefrijol Just to double-check: How will your guides differ from this page http://global.census.okfn.org/tutorial/

**Comment by morchickit** [comment]
See GODI 2015 guide - https://docs.google.com/document/d/1UoL272Q97RmdHS9wMT_ahu5ClQXkzwPlXKUjKAOwwl8/edit

**Comment by dannylammerhirt** [comment]
A main difference is question B3: 

Reviewers have to make sure the dataset contains some of the characteristics. Some submitters might state that the data is not collected at all (B1), or not available online at all (B2.1). They might base this assessment on the fact that not all dataset characteristics are provided. 

- [ ] Danny to do: define when does a dataset submission count as valid (if partial characteristics are in? if all characteristics are provided?)
