### ISSUE TITLE
Finalise questions

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#805]
!

**Comment by dannylammerhirt** [comment]
The final set of questions will directly be directly integrated by Danny in this spreadsheet from which @brew will pull the information: https://docs.google.com/spreadsheets/d/1aBBx8h9j8YW6nDaCoh8R0wWX-YCkqRZ8G0vgyPnGzwI/edit?pli=1#gid=235252093

If @KateRogers wishes to do changes these should be done directly in abovementioned sheet. 

To dos:

- [ ] final check of formulations that may be misunderstanding for submitters
- [ ] upload into abovementioned spreadsheet by Danny
- [ ] sign-off by @KateRogers

**Comment by pwalsh** [comment]
we are live, so must be done!
