### ISSUE TITLE
Ship dataset definitions and characteristics for the website

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#806]
!

**Comment by dannylammerhirt** [comment]
The dataset definitions and characteristics will directly be integrated in this file: https://docs.google.com/spreadsheets/d/1aBBx8h9j8YW6nDaCoh8R0wWX-YCkqRZ8G0vgyPnGzwI/edit?pli=1#gid=235252093

**Comment by pwalsh** [comment]
live so must be done!
