### ISSUE TITLE
Write FAQ

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#807]

**Comment by dannylammerhirt** [comment]
The FAQ page displays generally asked questions about the Index. The new FAQ text can be found here: https://docs.google.com/document/d/1BSDqhO9aJReAVDa_92e1KOgF35XRojk1_xAearx5_ag/edit#heading=h.u01hp8ww5j1e

To dos:

- [ ] Danny to check if there is info to add to the current page
- [ ] Danny to update any old content (references to 2015 edition, etc.)
- [ ] @KateRogers to sign-off

**Comment by morchickit** [comment]
Danny's task for this on the research board - https://trello.com/c/8yF44xvq/151-write-up-text-skeletons-for-all-current-texts

**Comment by dannylammerhirt** [comment]
@KateRogers I can only provide tips and tricks for the datasets I looked at (4 in total)

Who is write up tips for the remaining datasets? @morchickit or @tlacoyodefrijol ?

**Comment by morchickit** [comment]
I guess this is done if this is live? http://global.survey.okfn.org/faq/ 
@dannylammerhirt ?
