### ISSUE TITLE
Write Methodology

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#808]

**Comment by dannylammerhirt** [comment]
For the GODI website (http://index.okfn.org) we will again provide a methodology section (http://index.okfn.org/methodology/). This section needs to clarify changes we made compared to last year's edition, and explain our rationale to do so. It has to contain following elements: 
- [ ] research question 
- [ ] research assumptions   
- [ ] explanation of our dataset definitions
- [ ] explanation of dataset changes
- [ ] description of the places we cover 
- [ ] explanation of scoring
- [ ] explanation of the final possible scoring
- [ ] survey flow and conditions list
- [ ] sampling methodology
- [ ] assessment and quality review process

**Comment by morchickit** [comment]
Danny's tasks on the research board - https://trello.com/c/8yF44xvq/151-write-up-text-skeletons-for-all-current-texts
