### ISSUE TITLE
Synchonizing content for Tutorials (both for submitter and reviewer) and Methodology

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#813]
The GODI survey will provide additional information to clarify our methodology and to guide submitters (researcher guidance). Since the researcher guidance is informed by the methodology Danny and @tlacoyodefrijol have to synch their work. 

To dos:
- [x] clarify which guidance @tlacoyodefrijol will provide for submitters and reviewers in the video tutorials  
- [x] discuss if Danny needs to provide additional information for the Video tutorials 
- [x] discuss if we need a written tutorial section 
- [x] check if there is any content overlap across Tutorial and Methodology

**Comment by dannylammerhirt** [comment]
Clarified that we are gonna put detailed tips and tricks into a written FAQ section. These tips shall include info on how to find and assess different datasets 

To do
- [ ] Danny to insert tips and tricks into FAQ page

**Comment by morchickit** [comment]
What's the stauts on this? I can close it, no?

**Comment by dannylammerhirt** [comment]
@morchickit yes, this can be closed
