### ISSUE TITLE
Design criteria for when we accept submissions

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#817]
Like in the past edition of GODI, we are expecting submitters to answer the questions with reference to datasets that meet our minimum criteria. These minimum criteria have been part of the dataset description texts in 2015, but will now be contained in our characteristics question. Reviewers will look at submissions and will have to decide whether we accept a submission. For example, we won't accept a submission for government spending, if the dataset doesnt contain the amount of money paid per transaction. 

To dos:
- [ ] @KateRogers to develop a preliminary list of minimum criteria
- [ ] Danny to review the list

**Comment by morchickit** [comment]
@dannylammerhirt can I close it and move it to as part of the reviewers guide, see #799

**Comment by dannylammerhirt** [comment]
@morchickit yes, this is a sub-task for the reviewers guide.
