### ISSUE TITLE
Highlight difference between proposed answer and current entry answer

### ISSUE THREAD

**Issue by brew** [okfn/opendatasurvey#825]
This is useful for the review form. This has been designed in the mockup as part of #792.

<img width="924" alt="screen shot 2016-10-28 at 15 40 08" src="https://cloud.githubusercontent.com/assets/3993/19810362/0fb9ea2e-9d25-11e6-9bb7-73f396e8b0e1.png">

**Comment by morchickit** [comment]
Since it is useful for the review stage, I am moving this to Jan sprint.

**Comment by dannylammerhirt** [comment]
@morchickit can this be closed?

**Comment by morchickit** [comment]
yes!
