### ISSUE TITLE
Markup changes for survey Entry page

### ISSUE THREAD

**Issue by brew** [okfn/opendatasurvey#843]
The survey Entry page, available once an entry has been approved after review, needs mark up changes based on the mockup http://okfnlabs.org/census-mockup/entry/. This is related to the general issue about markup #785.

**Comment by pwalsh** [comment]
- [ ] Breadcrumbs
- [x] Dataset title (links to dataset page)
- [x] Place name (links to place page)
- [x] Social media section
- [ ] Data quality
  - [ ] Badge (status, last checked)
  - [ ] ? What's this ?
- [x] What data is expected?
  - [x] dataset description
  - [x] dataset characteristics
    - [ ] notify if this entry has the actual characteristic or not (e.g.: X or V next to each characteristic)
    - [ ] ? What's this ? (explains what the characteristics are)
- [ ] What data is available (change tile?)
  - [ ] icon is a clickable link to question description in popup
  - [ ] actual question text
  - [ ] design for 
    - [ ] URL and array of URLs
    - [ ] choice from select list (format)
    - [ ] 
- [ ] metadata section - must cover all additional questions, inc. scaled questions (e.g.: 2/3, 3/5), and inlined comment section. some sections can be labeled as "beta", such as "findability of data"
- [ ] reviewer comment box (at the bottom)
- [ ] TBD (*still in process*)

**Comment by pwalsh** [comment]
@dannylammerhirt can you please explain:

"displaying conditional information. This includes: "Following government agency / organisation collects the data: Submitter's response"; "The data are not collected by government for following reasons: Submitter's response")"

**Comment by dannylammerhirt** [comment]
So our first survey question is whether data is collected by government. Submitters have to provide explanations why they answer with "Yes" or "No" (this is what is meant by conditional information). 

In the case of a yes answer, they have to tell us the name of the government agency (in a blank text field). It would be good to display somewhere which government agency provides the data. 

In the case of a "no" answer, submitters necessarily have to provide info why government does not collect this data (in a blank text field). Assuming that all icons are red (indicate "no") it would help to interpret the results to have this explainer displayed somewhere. 

Both info does not have to be displayed under the "What data is available" header. It can also be presented under a standalone header.

**Comment by pwalsh** [comment]
@brew is there a general pattern here was can rely on of "yes/no question with conditionally required explanation"?

**Comment by dannylammerhirt** [comment]
@pwalsh can you explain again what you documented in the metadata section 

("must cover all additional questions, inc. scaled questions (e.g.: 2/3, 3/5), and inlined comment section. some sections can be labeled as "beta", such as "findability of data"")

I tried to remember how this relates to the question which info to display here? Or was this rather a general note for you and @brew?

**Comment by brew** [comment]
> @brew is there a general pattern here was can rely on of "yes/no question with conditionally required explanation"?

@pwalsh Not really, no. The questions are related in the Question Set Schema but only so the explanation question will be displayed depending on the yes/no answer.

**Comment by morchickit** [comment]
@brew to implement this and then Sam will design

**Comment by dannylammerhirt** [comment]
Explanation of discoverability section:

The discoverability section should explain (I) where data was found, (II) what data was found, (III) how data was found, and (IV) how submitters assess findability.

The discoverability section will include the following fields labelled as "BETA":

**Where was what data found?**
"The data was found at: [List of URLs]"  (#977)
We will also add a comment describing the content of this URL (This is a string which can be retrieved from the "source description" field on the survey page. See survey question B2.2 in the survey page)

**How was data found?**
The discoverability section should also include how submitters found data online. To present this I propose to implement a sentence like: "The submitter(s) took following steps to find the data: [INSERT STRING]". The string can be retrieved from the survey question B2.4.

**How do submitters assess findability?**
Also the section should contain an assessment of the findability of data. I propose to implement following sentence: "The submitter assessed data discoverability as follows (1= It was not easy at all to find the data, 4= It was very easy to find the data): [INSERT LIKERT-SCALE].

**Comment by morchickit** [comment]
@smth to advise how to organise the page better
