### ISSUE TITLE
Push static Index output to S3 bucket

### ISSUE THREAD

**Issue by brew** [okfn/opendatasurvey#854]
Once a static site has been generated (#853), it's output needs to be pushed to an appropriate S3 bucket. Consider using:

https://github.com/mwishek/metalsmith-s3 - interactions with AWS

- [x] Determine how to associate a site with an S3 bucket
- [x] Using Metalsmith plugin to export generated site to associated bucket

**Comment by pwalsh** [comment]
@brew a subtle but potentially crucial point: pushing to S3 might be the same action as generating the site - streaming a range of files live to the bucket.

**Comment by brew** [comment]
Agreed - I've split generation and pushing into two separate Issues, but that doesn't necessarily reflect the final implementation structure. I'm keen to tackle generation and pushing separately during development, partly so as not to overload one issue.
