### ISSUE TITLE
Announce rename to survey

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#870]

**Comment by morchickit** [comment]
@tlacoyodefrijol - this should be done soon. Please post a message in the forum.

**Comment by tlacoyodefrijol** [comment]
>Name change for Open Data Census
> As some of you may have noticed while submitting to GODI or local surveys, we have changed the name domain address of the tool to the Survey. This name change hopes to make the difference between the tool we use to capture information and the Index itself. It is a change of name that we consider will serve better to the submitters and participant in general.

**Comment by morchickit** [comment]
looks good to me. @pwalsh , happy with this phrasing for the forum?

**Comment by pwalsh** [comment]
Yep
