### ISSUE TITLE
Record government/political reactions to submissions

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#875]
As a {Submitter} I want to know how governments react to my submission, so I can see if there are any political reactions following after the submission.

From @KateRogers :

    try to collect statements from governments after the Index, if we could tag these to the country and then have it appear somewhere on the page I could see that being a potentially interesting feature.

**Comment by tlacoyodefrijol** [comment]
Should we document reactions like the ones from recent days?

**Comment by morchickit** [comment]
@KateRogers , what do you think?

**Comment by morchickit** [comment]
We need to write users stories for different reactions to the index, so we can decide how to show it.

**Comment by KateRogers** [comment]
Two actions - When/if we reach out to governments for comment pre-release, we need to make sure to let them know (encourage?) that they have the opportunity to  have a public response that we will link to the results 

We should make sure to encourage any government that talks to us post release that they should share this feedback publically  

(thinking about this more, I think this will be really powerful. We (Mor and I) often cite government responses but there is no evidence outside of our inboxes that governments do engage with the Index - even when they aren't necessarily constructive).

**Comment by morchickit** [comment]
Now that we have the public debate stage, this should hopefully be easier to record.

**Comment by morchickit** [comment]
Ok, I started a basic spreadsheet here: 
https://docs.google.com/spreadsheets/d/1ONxttSFddW12-_e2WhOltzd35vk-iUUtrTcT1VDXLgQ/edit#gid=0

It should be populated as we go.
