### ISSUE TITLE
Balkans blog post

### ISSUE THREAD

**Issue by tlacoyodefrijol** [okfn/opendatasurvey#878]

**Comment by morchickit** [comment]
Is this for the review phase? For the result publication phase like last time?

**Comment by tlacoyodefrijol** [comment]
Number #877 will be about process. This one for publication.

**Comment by morchickit** [comment]
I am still confused. Please elaborate in the description what are the key messages for each blog.

**Comment by morchickit** [comment]
please update status @tlacoyodefrijol

**Comment by dannylammerhirt** [comment]
Any news here @tlacoyodefrijol
