### ISSUE TITLE
Create QA guide for Regional wranglers

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#881]
See last year's QA guide - 
https://docs.google.com/a/okfn.org/document/d/1l_fi9RqoNy6ItgIxPoa5NJMQB75UbmIZ9Jdci9pKKtM/edit?usp=drive_web

**Comment by morchickit** [comment]
As a first step, I recommend to @dannylammerhirt and @tlacoyodefrijol to actually do QA by themselves to see what can be the potential pitfalls. 
I think @dannylammerhirt should look at Germany and Austria, Oscar should look at Paraguay.

**Comment by dannylammerhirt** [comment]
@morchickit great, I added the task to the research Trello: https://trello.com/c/5Rojks21/191-review-qa-for-reviewers-guidance

**Comment by tlacoyodefrijol** [comment]
So tasks would be:

[] testing the current QA 
[] Updating the QA to the 2016 edition

**Comment by dannylammerhirt** [comment]
See final version here: 
https://docs.google.com/document/d/1op7c2-MCMohB2cjrxoDKgQ9iNwMM6ApBQeesrvEiKy4/edit#
