### ISSUE TITLE
Find and contract thematic reviewers

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#882]
- [ ] Budget - Anna / Diana 

- [x] Spending - Anna / Diana 

- [ ] Laws - Open North

- [ ] Elections results - 

- [ ] Company register - Evengalina

- [ ] National Map - Codrina 

- [ ] National Statistics 

- [ ] Draft Legistlation - Open North

- [ ] Locations - Codrina

- [ ] Administrative Boundries

- [ ] Pollutants - 

- [ ] Procurment - Prozoro?
 
- [ ] Water Quality - Nisha

- [ ] Land Ownership - Linsay Ferris 

- [x] Weather Forecast - Danny

**Comment by KateRogers** [comment]
https://drive.google.com/?authuser=0&usp=kix-move#my-drive?action=locate&id=1DM2hifGvMKxscALTctfmvUM8VR4lp-ykUXrMrxTyvMY&parent=0BwCiEMnFOs0tTjE5NmxrSkd1emc
