### ISSUE TITLE
Coordinate launch date with the Web Foundation

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#885]
We need to get a date from the Web Foundation for the Index, and what is expected of us (design of sire, etc.)

**Comment by dannylammerhirt** [comment]
To add to this: Carlos Iglesias and I were planning to discuss two related issues

- [ ] in which structure we are gonna exchange GODI's results
- [ ] how we are gonna present (e.g. visualize) the final results on the front-end of both websites (ODB and GODI)

**Comment by morchickit** [comment]
According to Katelyn, Barometer launch is going to be around May.
