### ISSUE TITLE
Priority countries for the index

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#889]
Since they always need to be chased. A LOT.

**Comment by morchickit** [comment]
@KateRogers - as out favorite American, we will need your help here. I should send Alex Howard an email about it, but do need you on stand by.

**Comment by KateRogers** [comment]
@morchickit I would send to Rebecca Williams as well (she is no longer working for the government) - Happy to do that and happy to submit if necessary. I can also chase James and Jean Noe for Canada

**Comment by morchickit** [comment]
@tlacoyodefrijol to add countries that still need to submit

**Comment by tlacoyodefrijol** [comment]
- [ ] Bolivia
- [ ] Cameroon
- [ ] Canada
- [ ] China
- [ ] Costa Rica
- [ ] Denmark
- [ ] -Ecuador
- [ ] Estonia
- [ ] Finland
- [ ] France
- [ ] Ghana
- [ ] Iran
- [ ] Ireland
- [ ] Jamaica
- [ ] Kenya
- [ ] Netherlands
- [ ] New Zealand
- [ ] Norway
- [ ] Peru
- [ ] Portugal
- [ ] Sout Korea
- [ ] South Africa
- [ ] Spain
- [ ] United States of America
- [ ] Uruguay
- [ ] Venezuela
- [ ] Vietnam

**Comment by morchickit** [comment]
I sent messages to Canada and Estonia. @tlacoyodefrijol - should I ping Denmark?

**Comment by morchickit** [comment]
Also, in perfect timing, Spain just sent a message :-) I pinged Netherlands, we will need help there so I am asking Lieke.

**Comment by tlacoyodefrijol** [comment]
I think Denmark would be great to ping @morchickit. Also Cameroon started submitting.
