### ISSUE TITLE
Create a data dump of all finalised pending submissions.

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#903]
This is in order to compare them to the reviewed submissions later. 

For that we need - 

- [x]  Danny to specify which data he needs from pending submission

- [ ] To download the pending submissions data on Monday 30.1.17

**Comment by dannylammerhirt** [comment]
Data template available at: https://docs.google.com/spreadsheets/d/1GrJKD9tDbOTw3CzDSiOeBGUaBQG7b7maEqUEuKbbDdc/edit#gid=0
