### ISSUE TITLE
Add at the rational of the data characteristic to the description of the datasets

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#905]
So the user will understand why we review the way we do

**Comment by dannylammerhirt** [comment]
Danny to insert characteristics from 
https://docs.google.com/document/d/1IRD1o1dcdMyfPP5Eyx6HeGHs2s_bb9JU9Acbn9u4N14/edit#

into spreadsheet:
https://docs.google.com/spreadsheets/d/1PvAsgLepIYiuIAJVVv2cYmU-ev83vrCIigM0XRjz3a0/edit#gid=1627046260

**Comment by dannylammerhirt** [comment]
I'm writing up the content in this document: https://docs.google.com/document/d/1h_a4r1SO58T0m31AAWz4ioPTRr7PrIomoc9a8Pev3B4/edit

We have to decide if we put this on a separate page (currently in methodology section which is too hidden. 

Highlighting data characteristics is super important (methodology-wise, but also for communication with civil society)

**Comment by dannylammerhirt** [comment]
Start after QA implementation is finished
