### ISSUE TITLE
How to show submitter's comments on entry page

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#911]
The survey of the Global Open Data Index allows submitters to enter comments for each question (A1 & 2, B1 to B9). The comment boxes were intended to improve the usability of the survey preventing submitters from scrolling up and down. This can lead to a "split" of comments across several comment boxes. In former GODI editions we had one comment box which was displayed as a block of text on each entry page.

For the GODI 2016 edition comments should be presented in a easily readable form on an entry page. 

My proposed non-technical solution: 
reviewers copy-paste comments from single comment boxes in the final reviewer comment box and add a marker [SUBMITTER'S COMMENTS].

What is your opinion, @morchickit  @brew?

**Comment by brew** [comment]
My understanding was that these per-question comments were indended to add context from the submitter to the reviewer, and were never intended for display on the entry details page.

**Comment by dannylammerhirt** [comment]
This makes sense. Thank you @brew
