### ISSUE TITLE
Discuss review findings with each reviewer

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#915]
The review will compile all findings through review diaries. These contain feedback on our survey, on our characteristics, and on the workflow of the survey. 

We use this info to write the final results report, to improve our survey, and to improve our submitter/reviewer guidance.

**Comment by morchickit** [comment]
@dannylammerhirt - please update status here

**Comment by dannylammerhirt** [comment]
Received diary for

- [ ] company registers 
- [ ] weather data
- [ ] national law
- [ ] draft legislation
- [ ] budget 
- [ ] spending
- [ ] election results
- [ ] air quality
- [ ] statistics
- [ ] water quality
- [ ] national maps
- [ ] administrative boundaries
- [ ] locations
- [ ] land ownership
- [ ] contracting

**Comment by dannylammerhirt** [comment]
All reviewers will need to write a blogpost. They should take into account why we see data gaps in countries. Are there no administrative procedures? No resources or money? Would be great to know
