### ISSUE TITLE
Analysis of submission results (using data dump as source)

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#918]
The GODI survey enabled us to collect more quantitative information around the availability of data characteristics. Not all submissions will end up in the final scoring because the review will filter all submissions that do not match with our dataset characteristics. 

We will analyse all submissions, how many dataset characteristics are published online in which countries, as well as whether they are open or not. While this is not included in the final score, the report will acknowledge progress made, as well as blockages that still need to be overcome

**Comment by morchickit** [comment]
@dannylammerhirt do we still want to do this or can we close this?
