### ISSUE TITLE
Finalise places for the index site

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#925]
@brew to let the team know how to deal with countries that don't have submissions this year in the survey site (do we need to delete them from the excel? leave as is?)

**Comment by brew** [comment]
I propose adding a `DisableForYears` column to the places spreadsheet in the CMS. We have a similar feature for excluding datasets.

**Comment by brew** [comment]
`DisableForYears` column loaded to places table by commit  9d1470bf78440cdd502c02a0e9e4d3629bf5e547.
