### ISSUE TITLE
Show more information on the approved submission page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#931]
The page (for example: http://global.survey.okfn.org/entry/al/law/), doesn't show the links we collected in the survey. Those are needed for the final review.

**Comment by dannylammerhirt** [comment]
We should also check which of the single open data parameters: "Available in bulk", etc. we changed in the current survey.

For example, we check of data is available in open and machine-readable formats. So we should change the wording from machine-readable to "available in open and machine-readable formats"

The same goes for "available in bulk", it should be changed to "downloadable at once".

**Comment by dannylammerhirt** [comment]
Also we should highlight the name of the data producer/holder/publisher (available at question B1.1) so we see who published the data

**Comment by brew** [comment]
Entry data to be added to this page in a very basic way to aid review.

- [ ] source
- [ ] format
- [ ] license url
- [ ] characteristics
