### ISSUE TITLE
Rewriting description of reject button (survey page)

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#937]
A lot of reviewers were confused by the current description of the reject button on our survey page.
It states: 

"Reject will reject the submission and allow a new submission to be proposed. It should be used if question B1 or B2 have been answered with "No".

Reviewers think they have to reject EVERY submission with B1 or B2 = No, also those where B1 (is data collected by government?) and B2 (is the data available online?) have *correctly* been answered with  "No". However, the reject button shall be used if submitters have found some of the required data characteristics, but continued the survey anyway (i.e. did not answer B2 with "No" as they should have done).

To clarify I propose to rewrite the description. It shall state:

"Reject will reject the submission and allow a new submission to be proposed. It should be used  if submitters did not find all required data characteristics, but continued the survey anyway (i.e. did not answer B2 with "No", as they correctly should have done).

**Comment by brew** [comment]
@dannylammerhirt Do you want me to update the template with this new wording?

**Comment by dannylammerhirt** [comment]
@brew Yes, the old wording was confusing for reviewers. The new wording should be clear
