### ISSUE TITLE
Sending reviewers a list of countries that had submissions for all data categories

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#938]
In one specific case reviewers shall reject a submission. A rejection deletes the current submission entry from the list of submissions (see: global.survey.okfn.org).

The problem: 
If one reviewer does not immediately resubmit, other reviewers will not see that there has been a submission before it was rejected.

Some reviewers might think that not all data categories have been assessed by a submitter for this country, and they might not review this country.

Solution:
- [x] Danny to share a list of all our countries that have had one submission for all data categories

**Comment by morchickit** [comment]
depends on #925 answer.

**Comment by morchickit** [comment]
This is done. Now the survey only show the places that are in the sample
