### ISSUE TITLE
Renaming data category "pollutant emission" into "Air Quality" (for GODI edition 2017)

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#951]
The  data category "pollutant emission" measures the concentration values of air pollutants across a country. This type of information is usually not considered to be pollutant emission. Technically correct, pollutant emission is measured at the emission source (a chimney or sth.).

What we measure is usually called "air quality". Environmental protection agencies call it like that, and submitters will find pollutant concentration under this term online too. 

To better guide submitters (and to align with agreed upon terminonlogy), I propose to rename the category.

**Comment by morchickit** [comment]
@brew - can we do it now in the dataset or will it mess up everything? I think as long as the slag stays the same we are fine, right?

**Comment by brew** [comment]
If this category is renamed, then it will be renamed for all years. Is that what you want? Another way to tackle it would be to create a new dataset with the new name, and use the DisableForYears feature to prevent the old dataset from appearing in 2017.

**Comment by morchickit** [comment]
I think that renaming it for all years should not be a problem, since the criteria didnt change. @dannylammerhirt ?

**Comment by brew** [comment]
In that case, you can change the `Name` column, but **NOT** the `ID` column, in the spreadsheet!

**Comment by morchickit** [comment]
Changed
