### ISSUE TITLE
Update the community about the GODI timeline

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#954]
From now until Launch!

**Comment by morchickit** [comment]
Draft is here: 
https://docs.google.com/document/d/1gZaEfeiWZNt9vsKsyT1lCV51zSwGKts-v4TlWsEeyoc/edit

**Comment by dannylammerhirt** [comment]
Added my suggestions

**Comment by morchickit** [comment]
And it's live!

**Comment by tlacoyodefrijol** [comment]
![yay](https://media.giphy.com/media/kiblLDUFurYI0/giphy.gif)
