### ISSUE TITLE
Write a blogpost on how to "read" the GODI results

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#955]
**What**
The GODI survey is built so that it assesses different degrees of openness. 

Some variations are (@morchickit we should discuss whether my definitions below are commonly used - they are somewhat similar to https://theodi.org/data-spectrum) :

- **Data  under closed access:** accessible after data was requested, paid for, etc. It is machine-readable, but not openly licensed.

- **Data under public access:** available online for free in HTML, but is not downloadable, maybe also not openly licensed

- **Data under open access:** data accessible to download, it's openly licensed, machine-readable 

Why is it important to differentiate:

- GODI evaluates each of these access types
- Often reviewers need to make a decision which datasets to take as reference point. Their decision can affect a country score, if there is for example a closed or a public dataset. Possibly the scores of both datasets might be similar. But in some cases they won't.
- Our scores somewhat reflect different access types: A score below 100% is either no access, closed access or public access. 
- We need to highlight that every score below 100% is not open data. We should instead take into account that we assess different degrees of openness.
- Our results show green/red coding. To make it readable for laypersons we could add tags such as public access, closed access, no access.

Deliverables
- write a blogpost
- add tags to the survey page?

**Comment by morchickit** [comment]
@dannylammerhirt why is this assigned to me?

**Comment by morchickit** [comment]
Never mind, now I saw it is also to you and @tlacoyodefrijol

**Comment by dannylammerhirt** [comment]
Implement this information somewhere on the website

**Comment by morchickit** [comment]
Add a paragraph about it for the about page

**Comment by dannylammerhirt** [comment]
Blogpost here:  https://docs.google.com/document/d/1x8pacm1jppros7J6mlczYTjGQ_yg3sK_uRxRUK0DFBM/edit

**Comment by dannylammerhirt** [comment]
@morchickit, @tlacoyodefrijol can one of you read this post, mark what is not clear, sanity-check? Maybe if you have nice images and examples, feel free to add them

**Comment by morchickit** [comment]
Ok, this is now on the site. We need to make a shorter blog post.

**Comment by dannylammerhirt** [comment]
Shorter blogpost version here: https://docs.google.com/document/d/1R2_SMi7sm3VLMdeocn33KYVZ1pHPsGJoFc-Vlb58YE8/edit#heading=h.e3eicvvm156l

**Comment by morchickit** [comment]
@dannylammerhirt I edited the blog version in cut it half. It is in the blog CMS so please have a look there. Is in draft mode so please dont publish it yet. I will publish it on Tuesday.

**Comment by dannylammerhirt** [comment]
Looks good to me, ready to publish
