### ISSUE TITLE
Add Google Analytics to the Index results site

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#959]
This task is to remind us to add the analytics code to the config sheet

**Comment by morchickit** [comment]
We need this so we can track the Index use

**Comment by brew** [comment]
This is available as a setting in the Index Config sheet of the CMS spreadsheet.

**Comment by morchickit** [comment]
@brew - according to the spreadsheet we have populated the spreadsheet with the current analytics, right?

**Comment by brew** [comment]
Yep - this is done.
