### ISSUE TITLE
Maps visualization for Index

### ISSUE THREAD

**Issue by brew** [okfn/opendatasurvey#967]
This issue exists so we don't lose sight of the map visualization for the Index site.

Currently, the maps visualization doesn't use live data from the site, and it may not be appropriate for it to use the 'year' dropdown with the new methodology. I'm not sure how the map gets its data (if it's live or hardcoded).

Do we want to redesign the map visualization for this year (2016)?

Would it be much work to allow its use for Local Index sites?

The current map is described well in the old [Index README](https://github.com/okfn/opendataindex/blob/fc749fea592e59e811a8cd7eefb1205234295bc4/README.md#visualisations).

- [x] /data directory (see also #969)
- [ ] permalink /vis/map
- [ ] embed link /vis/map/embed
- [x] default `uiStateDefaults` object
- [ ] URL param settings
- [x] `embed_title` map var
- [x] Country link from map (should link using 2-letter country code)
- [x] Map for Index page (#995)
- [x] Map for /place/<id> page
- [x] Map for  #/dataset/<id> page

**Comment by morchickit** [comment]
@pwalsh - Can you please give more info about the map? I think you were the last one to work on it. If we do need to some extra work on it, will be good to know know some estimates

**Comment by pwalsh** [comment]
@morchickit @brew I don't understand. I built the original map, and last year others fixed all known bugs. What change is needed at all?

**Comment by brew** [comment]
@pwalsh Can you briefly outline how the map works? Where it gets its data from, etc.?

**Comment by pwalsh** [comment]
- Here is the base template for map: https://github.com/okfn/opendataindex/blob/master/themes/odi/templates/map.embed.html
- Here is where the data is build: https://github.com/okfn/opendataindex/blob/master/themes/odi/static/scripts/map/data.js
- The map can be embedded, as we as the permalink routes: https://github.com/okfn/opendataindex/blob/master/themes/odi/templates/map.permalink.html
- The javascript is bootstrapped with require.js : https://github.com/okfn/opendataindex/blob/master/themes/odi/static/scripts/site.js#L1
- And specifically the map is bootstrapped with require.js: https://github.com/okfn/opendataindex/blob/master/themes/odi/static/scripts/map.js#L1
- All the non-vendor map logic is in https://github.com/okfn/opendataindex/tree/master/themes/odi/static/scripts/map
