### ISSUE TITLE
Explain what data are we looking for behind a dataset

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#976]
Original request on #843 :
- dataset description incl. 2-3 sentences why GODI assesses this data (to be included)
-  dataset characteristics
    - list all characteristics
    - add notes which characteristics are required or optional

To implement:
- Include description of the dataset. In the content, make sure it describes which characteristics are required or optional 
- Include the  list all characteristics

**Comment by morchickit** [comment]
@dannylammerhirt to make sure this is in the spreadsheet. @brew for reference

**Comment by dannylammerhirt** [comment]
Working document: https://docs.google.com/document/d/1VQAPU5KF-qegcZQjdLjHdrtIK5zTslopk96IdLRaxpU/edit

**Comment by dannylammerhirt** [comment]
- [x] Budgets
- [x] Spending
- [x] Elections
- [x] Land ownership
- [x] Procurement
- [x] Company Registers
- [x] National maps 
- [x] Administrative boundaries 
- [x] locations 
- [x] National statistics
- [x] Air quality
- [x] Draft legislation 
- [x] National law
- [x] Weather forecasts
- [x] Water quality
