### ISSUE TITLE
Election result category

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#983]
@dannylammerhirt - what is the status there? I see that countries that were closed last year (i.e UK or Canada) are now getting full scores of open. What was the decision there?

**Comment by morchickit** [comment]
@tlacoyodefrijol - FYI when you do review about Poll stations level. Park QA on elections until Danny is back

**Comment by dannylammerhirt** [comment]
@morchickit Paola told me she wanted to correct all reviews that are not at polling station level. I'll catch up with her today

**Comment by morchickit** [comment]
This has a duplicate #992 . Closing this one.
