### ISSUE TITLE
Licenses that need to be check and we need to decide if they are open or not

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#986]
Based on my question in the forum:
https://discuss.okfn.org/t/singapore-open-data-license/4927/2

Countries I have ponders about so far:

- [x] Singapore

- [x]  Denmark 

- [x]  France

- [x] Israel

- [x] Czech Republic 

All seems open license, but not vetted by the open definition group...

**Comment by dannylammerhirt** [comment]
We will use following methodology to assess compliance with the Open Definition: https://docs.google.com/document/d/191jO8JdrVXhyWsqldHcHVmz3KPsNhlYTqZXx6LdCqwk/edit

**Comment by dannylammerhirt** [comment]
Methodology got signed off by Freyja, all fine.

**Comment by dannylammerhirt** [comment]
Put into methodolgy
