### ISSUE TITLE
Contract Nisha for Water quality data use research

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#987]
This task is post survey content and research work. It is part of our deliverable for Hewlett. 
From the Hewlett proposal: We will support open data communities to bring both topical and technical experts to assess their own government’s data publication to date.  Open Knowledge International will work with our partner organisations to design engagement opportunities that ensure that the open data community is able to effectively engage with experts from a variety of fields. How these events and activities are structured will be very much dependant on expertise and positioning of our local partners. 

Nisha and Datameet will be contracted through Internet and Society to look at water quality part of the index and to engage communities with it. 
This will include the following outputs:
1.  Survey template for a organisations and community groups who work in water access and public health.
2. One event with open data activists, developers and water sector groups to come up with datasets, use cases, tools, and other projects that better quality data can create. A tool (activity, survey, app) for people to interact with data about water 
3. Documentation of the survey results from the South Asia groups, the process to create the survey, and a literature review. 

@pwalsh we should discuss this before our call with the Web Foundation.

**Comment by dannylammerhirt** [comment]
@morchickit If I understand correctly Nisha's results are also relevant for this issue: https://github.com/okfn/opendatasurvey/issues/957

**Comment by morchickit** [comment]
Yes! We should connect it.

**Comment by morchickit** [comment]
The contract is signed. @dannylammerhirt - We need to do a handover on this!
