### ISSUE TITLE
Blogpost: Data quality and our learnings (Draft ready by May 19)

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#988]
Call for a better understanding of data quality here: 
https://docs.google.com/document/d/1bTUhGGDdjBDsYC3WcdKYQAZGhsPTTFCY8-NYGy1teKY/edit#heading=h.skeyinovjuwu

**Comment by morchickit** [comment]
To accompany the index launch

**Comment by dannylammerhirt** [comment]
Make sure to mention that we constantly see trade-offs between data qualities. There is not one definition of good quality. But what is data lies in the eye of the beholder 


Make sure to cover different data types

- [ ] Check draft legislation and national law for text-based data

- [ ] check weather data

- [ ] check GIS data

**Comment by dannylammerhirt** [comment]
Refer to OKDE blogposts [here](https://okfn.de/blog/2017/04/Making-EU-Data-Open/?utm_content=bufferf02ea&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) and [here](https://okfn.de/blog/2017/04/esif-data-quality-index/)

**Comment by dannylammerhirt** [comment]
Very drafty blogpost draft here: https://docs.google.com/document/d/11dKN0vwNOqmSC7qUBLZS6cUnZR7EfVUjAxJsuRFV-lA/edit

**Comment by dannylammerhirt** [comment]
Write a statement why we removed HTML

**Comment by dannylammerhirt** [comment]
Danny to share draft blogpost with Carlos and Ana
