### ISSUE TITLE
Write why we separate Northern Ireland from Great Britain (and similar cases)

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatasurvey#990]

**Comment by morchickit** [comment]
Mor to hide NI and to write that there data about it for comparison for the future

**Comment by morchickit** [comment]
https://docs.google.com/document/d/1CrJS_Sy9Qc6xnu-tfSAlkGTHSUQPkV8phVW2Zd7msE0/edit

**Comment by morchickit** [comment]
NI disabled in GODI and is not showing. Closing this. 
@dannylammerhirt - please review the text.

**Comment by dannylammerhirt** [comment]
@morchickit reviewed. Maybe another one can look over it to check readability.

**Comment by morchickit** [comment]
@dannylammerhirt to do a short analysis and comparison between UK (which should be name GB) and NI

**Comment by dannylammerhirt** [comment]
Comparative 1 pager here: https://docs.google.com/document/d/17w76HYD3vd12FQjlMbGj2-0FX05h4w43A9F9orDYzkg/edit#

**Comment by nickmhalliday** [comment]
@dannylammerhirt the official title of GB and NI is: The United Kingdom of Great Britain and Northern Ireland as described [here](https://country.register.gov.uk/records?page-index=2&page-size=100)

**Comment by morchickit** [comment]
And the latest version is here: https://docs.google.com/document/d/17w76HYD3vd12FQjlMbGj2-0FX05h4w43A9F9orDYzkg/edit#

**Comment by dannylammerhirt** [comment]
Our blogpost will be edited in this file:

**Comment by dannylammerhirt** [comment]
Ready for proofreading, @morchickit

**Comment by dannylammerhirt** [comment]
A comparison of remits on Open Data dataset by dataset (by Suzanne McLaughlin) is here: https://docs.google.com/document/d/1qMk25BfZhZMnmk2zlGnInYBxfgJMHLjl-69aQ3O6-mQ/edit

and here: https://docs.google.com/document/d/1RGfUt7XlJA1um54JwlJZap7EMU1hZ_ZLZ4kQg74IVDw/edit

**Comment by dannylammerhirt** [comment]
We will store all information on this topic  here: https://drive.google.com/drive/folders/0B5j55T4ZyssBNU9tMHZQZ3NIOTQ

**Comment by dannylammerhirt** [comment]
@morchickit what is the latest status here?
