### ISSUE TITLE
Ranking in Survey and Index are not consistent

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#991]
Places for the same scores are not aligned, see the following screenshot where countries with the same score got different ranks. 
![screen shot 2017-03-29 at 00 04 39](https://cloud.githubusercontent.com/assets/3273659/24431400/93b1a8de-1413-11e7-84a2-9b2bd7a4532e.png)

@brew  to check if this is because of the raw value

**Comment by brew** [comment]
Closed by 56747da134a17f33368223048cd51bf5a39209d7
