### ISSUE TITLE
No index settings

### ISSUE THREAD

**Issue by martinszy** [okfn/opendatasurvey#997]
Hello, I would like to create the site for the Argentina local city census and I find the button disabled with the message (No Index Settings for site)

Also reported here:
https://discuss.okfn.org/t/no-index-settings-for-site/4940

**Comment by morchickit** [comment]
yes, the index generated site is currently only enabled for the Global Open Data Index. See issue #966 to see what is needed to generate local census (hint - we need people to contribute code!)
