### ISSUE TITLE
Add methodology to the index site

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#998]
Update content on the spreadsheet

**Comment by morchickit** [comment]
Make sure the following is included:
1. Our research question
2. Our assumption 
3. Our datasets and why we choose them
4. Our sample and what does it mean
5. Our scoring and why we score like we score #955 
6. How do we review, why we review like that and who are our reviewers?
7. How to contest the result and why do we do it?

**Comment by dannylammerhirt** [comment]
https://github.com/okfn/opendatasurvey/issues/986

**Comment by dannylammerhirt** [comment]
Add QA of false positives to methodology

**Comment by dannylammerhirt** [comment]
Find the working document (for copy) here: https://docs.google.com/document/d/1cpaK_fN22xbiHqRxDu_a7fc8xgDgy6fpiIMoPUqeIs8/edit#heading=h.3jkrly5i1rd4

**Comment by dannylammerhirt** [comment]
Add a note why we change methodology

**Comment by dannylammerhirt** [comment]
- [ ] why do we assess places instead of countries?

**Comment by dannylammerhirt** [comment]
- [ ] update our scoring explanations https://docs.google.com/document/d/1jwK_UmWMkj1xz7LFhsttQQW34jJb1atr9AuJ_-vHk5M/edit#

**Comment by dannylammerhirt** [comment]
@morchickit methodology is ready and can be read through
